import { BacktestConfig, BacktestStrategyId, StrategyDefinition } from './types';

export const STRATEGY_CATALOG: StrategyDefinition[] = [
  {
    id: 'covered_call',
    name: 'Covered Call',
    shortName: 'CC',
    phase: 1,
    status: 'foundation',
    description: 'Azioni in portafoglio coperte economicamente da call vendute.',
    legs: [
      { role: 'Copertura', description: '100 azioni per contratto short call', required: true },
      { role: 'Call venduta', description: 'Call short con quantità coerente con la copertura', required: true, canBeTemporarilyMissing: true },
    ],
    entryRules: ['Finestra DTE', 'Strike per delta o distanza OTM', 'Liquidità minima', 'Premio minimo'],
    managementRules: ['Take profit', 'Avvicinamento allo strike', 'Roll per DTE/delta', 'Credito netto configurabile'],
    exitRules: ['Chiusura prima della scadenza oppure assegnazione', 'Riapertura della call secondo frequenza configurata'],
  },
  {
    id: 'synthetic_covered_call',
    name: 'Covered Call sintetica',
    shortName: 'CC sintetica',
    phase: 1,
    status: 'foundation',
    description: 'La copertura azionaria è sostituita da esposizione sintetica, mantenendo separata la call venduta.',
    legs: [
      { role: 'Esposizione sintetica', description: 'Long call profonda ITM e/o combinazione long call + short put compatibile', required: true },
      { role: 'Call venduta', description: 'Call short di copertura', required: true, canBeTemporarilyMissing: true },
    ],
    entryRules: ['Coerenza quantitativa della copertura sintetica', 'DTE lungo sulla gamba di copertura', 'Liquidità su entrambe le scadenze'],
    managementRules: ['Roll separato della call corta', 'Controllo delta della copertura', 'Segnalazione esplicita di gamba da rivendere'],
    exitRules: ['Chiusura coordinata o trasformazione dichiarata', 'Mai riclassificare automaticamente quando manca una gamba'],
  },
  {
    id: 'de_risking_covered_call',
    name: 'De-risking Covered Call',
    shortName: 'DR CC',
    phase: 1,
    status: 'foundation',
    description: 'Famiglia CC gestita con finalità esplicita di riduzione del rischio, anche in variante sintetica e a 2/3 gambe.',
    legs: [
      { role: 'Copertura', description: 'Azioni o esposizione sintetica compatibile', required: true },
      { role: 'Call venduta', description: 'Call short con finalità de-risking', required: true, canBeTemporarilyMissing: true },
      { role: 'Protezione opzionale', description: 'Eventuale put protettiva o terza gamba configurata', required: false, canBeTemporarilyMissing: true },
    ],
    entryRules: ['Finalità de-risking dichiarata', 'Budget di rischio prima del rendimento', 'Struttura a 2 o 3 gambe ammessa'],
    managementRules: ['Gambe gestite per ruolo', 'Stato incompleto senza cambio automatico di strategia', 'Roll coerente con la riduzione del rischio'],
    exitRules: ['Trasformazione solo se cambia payoff o finalità', 'Gamba mancante riportata come azione pendente'],
  },
  {
    id: 'cash_secured_put',
    name: 'Cash-Secured Put',
    shortName: 'CSP',
    phase: 1,
    status: 'foundation',
    description: 'Put venduta con liquidità sufficiente per l’eventuale assegnazione.',
    legs: [{ role: 'Put venduta', description: 'Short put interamente coperta da cassa', required: true }],
    entryRules: ['Strike per delta/OTM', 'Cassa riservata pari al rischio di assegnazione', 'Liquidità minima'],
    managementRules: ['Take profit', 'Roll per DTE/delta', 'Stop opzionale sul multiplo del premio'],
    exitRules: ['Buy-to-close o assegnazione', 'Nessuna esposizione naked se il flag è disattivato'],
  },
  {
    id: 'wheel',
    name: 'Wheel',
    shortName: 'Wheel',
    phase: 1,
    status: 'foundation',
    description: 'Ciclo automatico CSP → assegnazione azioni → Covered Call → eventuale richiamo.',
    legs: [
      { role: 'Fase put', description: 'Cash-secured put', required: true },
      { role: 'Fase azioni + call', description: 'Covered call dopo l’assegnazione', required: true },
    ],
    entryRules: ['Avvio da CSP', 'Capitale sufficiente per 100 azioni per contratto'],
    managementRules: ['Stato del ciclo persistente', 'Regole di roll distinte per put e call'],
    exitRules: ['Fine ciclo configurabile', 'Assegnazioni contabilizzate come transizioni, non come errori'],
  },
  {
    id: 'bull_put_spread',
    name: 'Bull Put Spread',
    shortName: 'Bull Put',
    phase: 2,
    status: 'planned',
    description: 'Vertical credit spread rialzista a rischio definito.',
    legs: [
      { role: 'Put venduta', description: 'Strike superiore', required: true },
      { role: 'Put comprata', description: 'Strike inferiore, stessa scadenza', required: true },
    ],
    entryRules: ['Credito minimo rispetto alla larghezza', 'Stessa scadenza', 'Liquidità su entrambe le gambe'],
    managementRules: ['Take profit sul credito', 'Stop sul multiplo del credito', 'Gestione tested side'],
    exitRules: ['Chiusura coordinata delle due gambe', 'Regole di assegnazione esplicite'],
  },
  {
    id: 'bear_call_spread',
    name: 'Bear Call Spread',
    shortName: 'Bear Call',
    phase: 2,
    status: 'planned',
    description: 'Vertical credit spread ribassista a rischio definito.',
    legs: [
      { role: 'Call venduta', description: 'Strike inferiore', required: true },
      { role: 'Call comprata', description: 'Strike superiore, stessa scadenza', required: true },
    ],
    entryRules: ['Credito minimo rispetto alla larghezza', 'Stessa scadenza', 'Liquidità su entrambe le gambe'],
    managementRules: ['Take profit sul credito', 'Stop sul multiplo del credito', 'Gestione tested side'],
    exitRules: ['Chiusura coordinata delle due gambe', 'Regole di assegnazione esplicite'],
  },
  {
    id: 'iron_condor',
    name: 'Iron Condor',
    shortName: 'Iron Condor',
    phase: 2,
    status: 'planned',
    description: 'Doppio credit spread a rischio definito.',
    legs: [
      { role: 'Put spread', description: 'Put short + put long', required: true, canBeTemporarilyMissing: true },
      { role: 'Call spread', description: 'Call short + call long', required: true, canBeTemporarilyMissing: true },
    ],
    entryRules: ['Delta indipendente per i due lati', 'Larghezze e scadenza coerenti', 'Credito totale minimo'],
    managementRules: ['Gestione lato testato', 'Chiusura o roll di una coppia senza perdere l’identità dichiarata'],
    exitRules: ['Chiusura coordinata', 'Gamba mancante sempre segnalata'],
  },
  {
    id: 'protective_put',
    name: 'Protective Put',
    shortName: 'Protective Put',
    phase: 2,
    status: 'planned',
    description: 'Azioni più put comprata come assicurazione.',
    legs: [
      { role: 'Azioni', description: 'Posizione long sul sottostante', required: true },
      { role: 'Put comprata', description: 'Protezione downside', required: true },
    ],
    entryRules: ['Budget assicurativo', 'Strike e durata della protezione'],
    managementRules: ['Rinnovo della protezione', 'Regole dopo rialzi o ribassi'],
    exitRules: ['Esercizio o vendita della put', 'Chiusura indipendente solo se dichiarata'],
  },
  {
    id: 'collar',
    name: 'Collar',
    shortName: 'Collar',
    phase: 2,
    status: 'planned',
    description: 'Azioni protette da put e finanziate in tutto o in parte da call venduta.',
    legs: [
      { role: 'Azioni', description: 'Copertura fisica', required: true },
      { role: 'Put comprata', description: 'Floor di protezione', required: true },
      { role: 'Call venduta', description: 'Cap e finanziamento', required: true },
    ],
    entryRules: ['Costo netto massimo', 'Floor/cap configurabili'],
    managementRules: ['Roll delle opzioni come coppia o per ruolo'],
    exitRules: ['Gestione assegnazione ed esercizio'],
  },
  {
    id: 'calendar_spread',
    name: 'Calendar Spread',
    shortName: 'Calendar',
    phase: 3,
    status: 'planned',
    description: 'Stesso strike con scadenze diverse.',
    legs: [
      { role: 'Opzione corta', description: 'Scadenza ravvicinata', required: true, canBeTemporarilyMissing: true },
      { role: 'Opzione lunga', description: 'Scadenza lontana', required: true },
    ],
    entryRules: ['Stesso strike e right', 'Term structure e debito massimo'],
    managementRules: ['Roll ripetuto della gamba corta'],
    exitRules: ['Valore residuo della gamba lunga incluso'],
  },
  {
    id: 'diagonal_spread',
    name: 'Diagonal Spread',
    shortName: 'Diagonal',
    phase: 3,
    status: 'planned',
    description: 'Strike e scadenze diversi, con gestione separata delle gambe.',
    legs: [
      { role: 'Opzione corta', description: 'Scadenza ravvicinata', required: true, canBeTemporarilyMissing: true },
      { role: 'Opzione lunga', description: 'Scadenza lontana', required: true },
    ],
    entryRules: ['Delta e DTE per ciascuna gamba', 'Debito massimo'],
    managementRules: ['Roll della gamba corta', 'Controllo copertura economica'],
    exitRules: ['Trasformazione dichiarata se cambia il payoff'],
  },
  {
    id: 'double_diagonal',
    name: 'Double Diagonal',
    shortName: 'Double Diagonal',
    phase: 3,
    status: 'planned',
    description: 'Diagonale put più diagonale call, anche temporaneamente incompleta.',
    legs: [
      { role: 'Lato put', description: 'Put corta + put lunga', required: true, canBeTemporarilyMissing: true },
      { role: 'Lato call', description: 'Call corta + call lunga', required: true, canBeTemporarilyMissing: true },
    ],
    entryRules: ['Regole indipendenti per lato put/call', 'Debito e rischio complessivi'],
    managementRules: ['Gamba mancante esplicita', 'Roll per ruolo senza riclassificazione automatica'],
    exitRules: ['Chiusura coordinata o trasformazione dichiarata'],
  },
];

export const DEFAULT_BACKTEST_CONFIG: BacktestConfig = {
  strategyId: 'covered_call',
  symbol: 'AAPL',
  startDate: '2024-01-01',
  endDate: '2024-12-31',
  initialCapital: 100_000,
  contracts: 1,
  barSize: 'eod',
  entry: {
    frequency: 'after_expiry',
    selectionMode: 'delta',
    targetDelta: 0.3,
    targetOtmPct: 5,
    minDte: 25,
    maxDte: 45,
    minOpenInterest: 100,
    minVolume: 10,
    maxBidAskSpreadPct: 15,
    minPremiumPct: 0.5,
  },
  management: {
    takeProfitPct: 50,
    stopLossMultiple: null,
    rollAtDte: 7,
    rollAtDelta: 0.7,
    rollAtStrikeDistancePct: 2,
    requireNetCredit: true,
    closeBeforeExpiry: false,
  },
  execution: {
    fillPriceModel: 'mid_with_slippage',
    slippagePctOfSpread: 10,
    commissionPerContract: 1,
    commissionPerShare: 0,
  },
  risk: {
    maxCapitalPerTradePct: 25,
    maxConcurrentPositions: 1,
    allowNakedOptions: false,
  },
};

export function getStrategyDefinition(id: BacktestStrategyId): StrategyDefinition {
  const strategy = STRATEGY_CATALOG.find((item) => item.id === id);
  if (!strategy) throw new Error(`Strategia non supportata: ${id}`);
  return strategy;
}
