-- Create underlying_mappings table for caching underlying name to ticker resolution
CREATE TABLE public.underlying_mappings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  underlying TEXT NOT NULL UNIQUE,
  ticker TEXT NOT NULL,
  source TEXT DEFAULT 'yahoo',
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- Enable RLS: public read, service role write
ALTER TABLE public.underlying_mappings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can read underlying mappings"
  ON public.underlying_mappings FOR SELECT USING (true);

-- Add trigger for updated_at
CREATE TRIGGER update_underlying_mappings_updated_at
  BEFORE UPDATE ON public.underlying_mappings
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

-- Seed initial data from hardcoded mappings (most common ones)
INSERT INTO public.underlying_mappings (underlying, ticker, source) VALUES
  -- Major US Tech
  ('APPLE COMPUTER, INC.', 'AAPL', 'manual'),
  ('APPLE COMPUTER INC', 'AAPL', 'manual'),
  ('APPLE INC', 'AAPL', 'manual'),
  ('APPLE INC.', 'AAPL', 'manual'),
  ('NVIDIA CORP', 'NVDA', 'manual'),
  ('NVIDIA CORPORATION', 'NVDA', 'manual'),
  ('MICROSOFT CORP', 'MSFT', 'manual'),
  ('MICROSOFT CORPORATION', 'MSFT', 'manual'),
  ('AMAZON.COM.INC', 'AMZN', 'manual'),
  ('AMAZON.COM, INC.', 'AMZN', 'manual'),
  ('AMAZON.COM INC', 'AMZN', 'manual'),
  ('AMAZON COM INC', 'AMZN', 'manual'),
  ('META PLATFORMS', 'META', 'manual'),
  ('META PLATFORMS INC', 'META', 'manual'),
  ('META PLATFORMS, INC.', 'META', 'manual'),
  ('FACEBOOK INC', 'META', 'manual'),
  ('ALPHABET INC', 'GOOGL', 'manual'),
  ('ALPHABET INC.', 'GOOGL', 'manual'),
  ('GOOGLE INC.', 'GOOGL', 'manual'),
  ('GOOGLE INC. (A)', 'GOOGL', 'manual'),
  ('ALPHABET INC-CL A', 'GOOGL', 'manual'),
  ('ALPHABET INC-CL C', 'GOOG', 'manual'),
  ('GOOGLE INC. (C)', 'GOOG', 'manual'),
  ('TESLA INC', 'TSLA', 'manual'),
  ('TESLA, INC.', 'TSLA', 'manual'),
  ('TESLA MOTORS INC', 'TSLA', 'manual'),
  ('NETFLIX INC', 'NFLX', 'manual'),
  ('NETFLIX, INC.', 'NFLX', 'manual'),
  ('ADOBE INC', 'ADBE', 'manual'),
  ('ADOBE SYSTEMS INC', 'ADBE', 'manual'),
  ('SALESFORCE INC', 'CRM', 'manual'),
  ('SALESFORCE.COM INC', 'CRM', 'manual'),
  ('PAYPAL HOLDINGS INC', 'PYPL', 'manual'),
  ('PAYPAL HOLDINGS', 'PYPL', 'manual'),
  ('INTEL CORP', 'INTC', 'manual'),
  ('INTEL CORPORATION', 'INTC', 'manual'),
  ('AMD', 'AMD', 'manual'),
  ('ADVANCED MICRO DEVICES', 'AMD', 'manual'),
  ('ADVANCED MICRO DEVICES INC', 'AMD', 'manual'),
  ('CISCO SYSTEMS INC', 'CSCO', 'manual'),
  ('CISCO SYSTEMS', 'CSCO', 'manual'),
  ('ORACLE CORP', 'ORCL', 'manual'),
  ('ORACLE CORPORATION', 'ORCL', 'manual'),
  ('ORACLE SYSTEMS INC.', 'ORCL', 'manual'),
  ('ORACLE SYSTEMS INC', 'ORCL', 'manual'),
  ('IBM', 'IBM', 'manual'),
  ('INTERNATIONAL BUSINESS MACHINES', 'IBM', 'manual'),
  ('QUALCOMM INC', 'QCOM', 'manual'),
  ('QUALCOMM INCORPORATED', 'QCOM', 'manual'),
  ('BROADCOM INC', 'AVGO', 'manual'),
  ('BROADCOM LTD', 'AVGO', 'manual'),
  ('UBER TECHNOLOGIES INC', 'UBER', 'manual'),
  ('UBER TECHNOLOGIES', 'UBER', 'manual'),
  ('AIRBNB INC', 'ABNB', 'manual'),
  ('AIRBNB', 'ABNB', 'manual'),
  ('COINBASE GLOBAL INC', 'COIN', 'manual'),
  ('COINBASE', 'COIN', 'manual'),
  ('PALANTIR TECHNOLOGIES INC', 'PLTR', 'manual'),
  ('PALANTIR', 'PLTR', 'manual'),
  ('SNOWFLAKE INC', 'SNOW', 'manual'),
  ('SNOWFLAKE', 'SNOW', 'manual'),
  ('CROWDSTRIKE HOLDINGS INC', 'CRWD', 'manual'),
  ('CROWDSTRIKE', 'CRWD', 'manual'),
  ('DATADOG INC', 'DDOG', 'manual'),
  ('DATADOG', 'DDOG', 'manual'),
  ('ZOOM VIDEO COMMUNICATIONS', 'ZM', 'manual'),
  ('ZOOM VIDEO COMMUNICATIONS INC', 'ZM', 'manual'),
  ('SHOPIFY INC', 'SHOP', 'manual'),
  ('SHOPIFY', 'SHOP', 'manual'),
  ('SPOTIFY TECHNOLOGY', 'SPOT', 'manual'),
  ('SPOTIFY TECHNOLOGY SA', 'SPOT', 'manual'),
  ('BLOCK INC', 'SQ', 'manual'),
  ('SQUARE INC', 'SQ', 'manual'),
  ('SERVICENOW INC', 'NOW', 'manual'),
  ('SERVICENOW', 'NOW', 'manual'),
  ('WORKDAY INC', 'WDAY', 'manual'),
  ('WORKDAY', 'WDAY', 'manual'),
  ('TWILIO INC', 'TWLO', 'manual'),
  ('TWILIO', 'TWLO', 'manual'),
  ('MONGODB INC', 'MDB', 'manual'),
  ('MONGODB', 'MDB', 'manual'),
  ('OKTA INC', 'OKTA', 'manual'),
  ('OKTA', 'OKTA', 'manual'),
  ('JPMORGAN CHASE', 'JPM', 'manual'),
  ('JPMORGAN CHASE & CO', 'JPM', 'manual'),
  ('JP MORGAN CHASE', 'JPM', 'manual'),
  ('J.P. MORGAN CHASE & CO.', 'JPM', 'manual'),
  ('BANK OF AMERICA', 'BAC', 'manual'),
  ('BANK OF AMERICA CORP', 'BAC', 'manual'),
  ('WELLS FARGO', 'WFC', 'manual'),
  ('WELLS FARGO & CO', 'WFC', 'manual'),
  ('GOLDMAN SACHS', 'GS', 'manual'),
  ('GOLDMAN SACHS GROUP', 'GS', 'manual'),
  ('MORGAN STANLEY', 'MS', 'manual'),
  ('CITIGROUP INC', 'C', 'manual'),
  ('CITIGROUP', 'C', 'manual'),
  ('VISA INC', 'V', 'manual'),
  ('VISA', 'V', 'manual'),
  ('MASTERCARD INC', 'MA', 'manual'),
  ('MASTERCARD', 'MA', 'manual'),
  ('AMERICAN EXPRESS', 'AXP', 'manual'),
  ('AMERICAN EXPRESS CO', 'AXP', 'manual'),
  ('BERKSHIRE HATHAWAY', 'BRK.B', 'manual'),
  ('BERKSHIRE HATHAWAY INC', 'BRK.B', 'manual'),
  ('BLACKROCK INC', 'BLK', 'manual'),
  ('BLACKROCK', 'BLK', 'manual'),
  ('JOHNSON & JOHNSON', 'JNJ', 'manual'),
  ('UNITEDHEALTH GROUP', 'UNH', 'manual'),
  ('UNITEDHEALTH GROUP INC', 'UNH', 'manual'),
  ('PFIZER INC', 'PFE', 'manual'),
  ('PFIZER', 'PFE', 'manual'),
  ('MERCK & CO', 'MRK', 'manual'),
  ('MERCK', 'MRK', 'manual'),
  ('ABBVIE INC', 'ABBV', 'manual'),
  ('ABBVIE', 'ABBV', 'manual'),
  ('ELI LILLY', 'LLY', 'manual'),
  ('ELI LILLY AND CO', 'LLY', 'manual'),
  ('MODERNA INC', 'MRNA', 'manual'),
  ('MODERNA', 'MRNA', 'manual'),
  ('WALMART INC', 'WMT', 'manual'),
  ('WALMART', 'WMT', 'manual'),
  ('COSTCO WHOLESALE', 'COST', 'manual'),
  ('COSTCO WHOLESALE CORP', 'COST', 'manual'),
  ('HOME DEPOT INC', 'HD', 'manual'),
  ('HOME DEPOT', 'HD', 'manual'),
  ('NIKE INC', 'NKE', 'manual'),
  ('NIKE', 'NKE', 'manual'),
  ('STARBUCKS CORP', 'SBUX', 'manual'),
  ('STARBUCKS', 'SBUX', 'manual'),
  ('MCDONALDS CORP', 'MCD', 'manual'),
  ('COCA-COLA CO', 'KO', 'manual'),
  ('COCA COLA CO', 'KO', 'manual'),
  ('PEPSICO INC', 'PEP', 'manual'),
  ('PEPSICO', 'PEP', 'manual'),
  ('PROCTER & GAMBLE', 'PG', 'manual'),
  ('PROCTER AND GAMBLE', 'PG', 'manual'),
  ('WALT DISNEY CO', 'DIS', 'manual'),
  ('DISNEY', 'DIS', 'manual'),
  ('DISNEY CO', 'DIS', 'manual'),
  ('EXXON MOBIL', 'XOM', 'manual'),
  ('EXXON MOBIL CORP', 'XOM', 'manual'),
  ('CHEVRON CORP', 'CVX', 'manual'),
  ('CHEVRON', 'CVX', 'manual'),
  ('BOEING CO', 'BA', 'manual'),
  ('BOEING', 'BA', 'manual'),
  ('CATERPILLAR INC', 'CAT', 'manual'),
  ('CATERPILLAR', 'CAT', 'manual'),
  ('3M COMPANY', 'MMM', 'manual'),
  ('3M CO', 'MMM', 'manual'),
  ('GENERAL ELECTRIC', 'GE', 'manual'),
  ('GENERAL ELECTRIC CO', 'GE', 'manual'),
  ('HONEYWELL INTERNATIONAL', 'HON', 'manual'),
  ('HONEYWELL', 'HON', 'manual'),
  ('LOCKHEED MARTIN', 'LMT', 'manual'),
  ('LOCKHEED MARTIN CORP', 'LMT', 'manual'),
  ('RAYTHEON TECHNOLOGIES', 'RTX', 'manual'),
  ('RTX CORPORATION', 'RTX', 'manual'),
  ('UNION PACIFIC', 'UNP', 'manual'),
  ('UNION PACIFIC CORP', 'UNP', 'manual'),
  ('AT&T INC', 'T', 'manual'),
  ('AT&T', 'T', 'manual'),
  ('VERIZON COMMUNICATIONS', 'VZ', 'manual'),
  ('VERIZON', 'VZ', 'manual'),
  ('T-MOBILE US INC', 'TMUS', 'manual'),
  ('T-MOBILE', 'TMUS', 'manual'),
  ('SPY', 'SPY', 'manual'),
  ('SPDR S&P 500 ETF', 'SPY', 'manual'),
  ('QQQ', 'QQQ', 'manual'),
  ('INVESCO QQQ TRUST', 'QQQ', 'manual'),
  ('IWM', 'IWM', 'manual'),
  ('ISHARES RUSSELL 2000', 'IWM', 'manual'),
  ('GLD', 'GLD', 'manual'),
  ('SPDR GOLD SHARES', 'GLD', 'manual'),
  ('EEM', 'EEM', 'manual'),
  ('ISHARES MSCI EMERGING', 'EEM', 'manual'),
  ('VTI', 'VTI', 'manual'),
  ('VANGUARD TOTAL STOCK', 'VTI', 'manual'),
  -- Additional mappings
  ('ALIBABA GROUP HOLDING LTD', 'BABA', 'manual'),
  ('ALIBABA', 'BABA', 'manual'),
  ('ALIBABA GROUP', 'BABA', 'manual'),
  ('CONSTELLATION ENERGY CORPORATION', 'CEG', 'manual'),
  ('CONSTELLATION ENERGY', 'CEG', 'manual'),
  ('COREWEAVE INC', 'CRWV', 'manual'),
  ('COREWEAVE', 'CRWV', 'manual'),
  ('NETEASE INC', 'NTES', 'manual'),
  ('NETEASE', 'NTES', 'manual'),
  ('LULULEMON ATHLETICA INC', 'LULU', 'manual'),
  ('LULULEMON', 'LULU', 'manual'),
  ('LULULEMON ATHLETICA', 'LULU', 'manual'),
  ('PROGRESSIVE CORP', 'PGR', 'manual'),
  ('PROGRESSIVE', 'PGR', 'manual'),
  ('SOUNDHOUND AI INC', 'SOUN', 'manual'),
  ('SOUNDHOUND AI', 'SOUN', 'manual'),
  ('SOUNDHOUND', 'SOUN', 'manual'),
  ('RIGETTI COMPUTING INC.', 'RGTI', 'manual'),
  ('RIGETTI COMPUTING INC', 'RGTI', 'manual'),
  ('RIGETTI COMPUTING', 'RGTI', 'manual'),
  ('RIGETTI', 'RGTI', 'manual'),
  ('JD.COM INC', 'JD', 'manual'),
  ('JD(JD.COM INC)', 'JD', 'manual'),
  ('JD.COM', 'JD', 'manual'),
  ('NUSCALE POWER CORP', 'SMR', 'manual'),
  ('NUSCALE POWER', 'SMR', 'manual'),
  ('NUSCALE', 'SMR', 'manual'),
  ('WESTERN DIGITAL CORP', 'WDC', 'manual'),
  ('WESTERN DIGITAL', 'WDC', 'manual'),
  ('KLA CORP', 'KLAC', 'manual'),
  ('KLA', 'KLAC', 'manual'),
  ('IREN LTD', 'IREN', 'manual'),
  ('IREN', 'IREN', 'manual'),
  ('PINDUODUO INC', 'PDD', 'manual'),
  ('PINDUODUO', 'PDD', 'manual'),
  ('REDDIT INC', 'RDDT', 'manual'),
  ('REDDITI INC', 'RDDT', 'manual'),
  ('REDDIT', 'RDDT', 'manual'),
  ('ROCKET LAB CORP', 'RKLB', 'manual'),
  ('ROCKET LAB', 'RKLB', 'manual'),
  ('APPLOVIN CORP', 'APP', 'manual'),
  ('APPLOVIN', 'APP', 'manual'),
  ('ASTERA LABS INC', 'ALAB', 'manual'),
  ('ASTERA LABS', 'ALAB', 'manual'),
  ('MICRON TECHNOLOGY INC', 'MU', 'manual'),
  ('MICRON TECHNOLOGY', 'MU', 'manual'),
  ('MICRON', 'MU', 'manual'),
  ('NEBIUS GROUP NV', 'NBIS', 'manual'),
  ('NEBIUS GROUP', 'NBIS', 'manual'),
  ('NEBIUS', 'NBIS', 'manual'),
  ('CELESTICA INC', 'CLS', 'manual'),
  ('CELESTICA', 'CLS', 'manual'),
  ('CLEANSPARK INC', 'CLSK', 'manual'),
  ('CLEANSPARK', 'CLSK', 'manual'),
  ('HIMS & HERS HEALTH INC', 'HIMS', 'manual'),
  ('HIMS & HERS HEALTH', 'HIMS', 'manual'),
  ('HIMS & HERS', 'HIMS', 'manual'),
  ('IONQ INC', 'IONQ', 'manual'),
  ('IONQ', 'IONQ', 'manual'),
  ('SUPER MICRO COMPUTER IN', 'SMCI', 'manual'),
  ('SUPER MICRO COMPUTER INC', 'SMCI', 'manual'),
  ('SUPER MICRO COMPUTER', 'SMCI', 'manual'),
  ('SUPERMICRO', 'SMCI', 'manual'),
  ('ACCENTURE PLC', 'ACN', 'manual'),
  ('ACCENTURE', 'ACN', 'manual'),
  ('FORTINET INC', 'FTNT', 'manual'),
  ('FORTINET', 'FTNT', 'manual'),
  ('OKLO INC', 'OKLO', 'manual'),
  ('APPLIED DIGITAL CORP', 'APLD', 'manual'),
  ('APPLIED DIGITAL', 'APLD', 'manual'),
  ('PALO ALTO NETWORKS INC', 'PANW', 'manual'),
  ('PALO ALTO NETWORKS', 'PANW', 'manual'),
  ('PALO ALTO', 'PANW', 'manual')
ON CONFLICT (underlying) DO NOTHING;